### ISSUE TITLE
Docker app don't run.

### ISSUE THREAD

**Issue by clabnet** [jellydn/platformatic-starter#69]
@jellydn  Thanks, but the docker app don't run. 

My test:

1. Pulled your changes. 
2. `pnpm i`
3. `pnpm build`
4. `pnpm start`       ==> It run on localhost:3042

Using docker :

1. `docker build --progress=plain --no-cache -t platformatic-starter .`
2. `docker compose up -d`
3. `http://localhost:3042'    ==>  **ERR_CONNECTION_REFUSED**

Using traefik ON and traefik OFF., same result.

_Originally posted by @clabnet in https://github.com/jellydn/platformatic-starter/issues/68#issuecomment-1806730815_

**Comment by jellydn** [comment]
Thanks @clabnet I've just fixed by change the from `127.0.0.1` to `0.0.0.0`.
